# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: home-pool
spec:
  addresses:
  - 10.0.0.230-10.0.0.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: home-adv
spec:
  ipAddressPools:
  - home-pool

